export const palette = {
  ivory: "#FDFBF7",
  paper: "#FFFFFF",
  charcoal: "#1A1C1E",
  charcoalElevated: "#2D2F31",
  slate: "#60646C",
  orange: "#FF5F1F",
  orangePressed: "#E5551C",
  orangeSoft: "#FFE2D9",
  beige: "#E8E4DE",
  border: "#D1CDC7",
  success: "#4CAF50",
  successSoft: "#E8F5E9",
  warning: "#FFC107",
  warningSoft: "#FFF8E1",
  danger: "#E53935",
  dangerSoft: "#FFEBEE",
  info: "#3B82F6",
  infoSoft: "#EAF2FF",
} as const;

export const colors = {
  background: palette.ivory,
  gridLine: palette.beige,
  surface: palette.paper,
  surfaceElevated: palette.charcoalElevated,
  textPrimary: palette.charcoal,
  textSecondary: palette.slate,
  textInverse: palette.ivory,
  border: palette.border,
  borderStrong: palette.charcoal,
  accent: palette.orange,
  accentPressed: palette.orangePressed,
  accentSoft: palette.orangeSoft,
  success: palette.success,
  successSoft: palette.successSoft,
  warning: palette.warning,
  warningSoft: palette.warningSoft,
  danger: palette.danger,
  dangerSoft: palette.dangerSoft,
  info: palette.info,
  infoSoft: palette.infoSoft,
  offline: palette.slate,
  pending: palette.warning,
  transparent: "transparent",
} as const;

export type PaletteColor = keyof typeof palette;
export type ThemeColor = keyof typeof colors;
