export const palette = {
  black: "#090909",
  bloodRed: "#D41414",
  darkRed: "#8F0D0D",
  warmPaper: "#F4F0E8",
  surfaceVariant: "#E0DDD6",
  white: "#FFFFFF",
  inkMuted: "#615E58",
  success: "#287A3D",
  successSoft: "#E2F0E5",
  warning: "#A66600",
  warningSoft: "#FFF0C7",
  danger: "#B30E0E",
  dangerSoft: "#F7DADA",
  info: "#245B91",
  infoSoft: "#DFEBF6",
} as const;

export const colors = {
  background: palette.warmPaper,
  gridLine: palette.surfaceVariant,
  surface: palette.warmPaper,
  surfaceElevated: palette.black,
  surfaceVariant: palette.surfaceVariant,
  textPrimary: palette.black,
  textSecondary: palette.inkMuted,
  textInverse: palette.white,
  border: palette.black,
  borderStrong: palette.black,
  accent: palette.bloodRed,
  accentPressed: palette.darkRed,
  accentSoft: "#F4D5D2",
  success: palette.success,
  successSoft: palette.successSoft,
  warning: palette.warning,
  warningSoft: palette.warningSoft,
  danger: palette.danger,
  dangerSoft: palette.dangerSoft,
  info: palette.info,
  infoSoft: palette.infoSoft,
  offline: palette.inkMuted,
  pending: palette.warning,
  transparent: "transparent",
  scrim: "rgba(9, 9, 9, 0.78)",
} as const;

export type PaletteColor = keyof typeof palette;
export type ThemeColor = keyof typeof colors;
